### ISSUE TITLE
Electoral district scoping

### ISSUE THREAD

**Issue by deivid-rodriguez** [podemos-info/decidim-module-votings#38]
Should we disable the nested form if the voting feature has no scopes enabled? Should we scope the nested forms to scopes inside the main voting scope if voting scopes are enabled?

Related to #36.

**Comment by leio10** [comment]
I understand that you are referring to a participatory space with no scopes enabled, aren't you?
In that case, I guess that we can disable electoral districts in that case. We probable won't use that, but seems to be the most logical solution.

I'm not sure if I'm understanding your second question, too many "scopes" for me :rofl:

**Comment by deivid-rodriguez** [comment]
Hehe totally. The thing is, the voting model has a "scopes enabled" checbox similar to the one for participatory spaces.

I fixed it in #3 but maybe it's not necessary?

**Comment by leio10** [comment]
Ok, I was checking in a participatory space with disabled scopes and I was not seeing it at all.

So, yes, I would remove the "scopes enabled" checkbox, since its defined at a higher level and I don't see any use of it.

Now I understand your second question, and I agree that the best solution would be to scope electoral districts to scopes inside the voting scope, but it's seem a bit complicated.

I would start validating just that all electoral districts are included in the voting scope. Using the participatory space scope as the root scope for the electoral district scope would be enough. 

Of course, it would be better to use the voting scope instead of the participatory scope, but I think is too complex to do it now. What do you think?

**Comment by deivid-rodriguez** [comment]
Shit, I should stop commenting from my phone and have breakfast instead 😁

**Comment by leio10** [comment]
I see your point, I would leave it as is now, because I'm not 100% sure if we can remove it. In any case, this is another reason to use the participatory scope as root for the electoral districts.

**Comment by deivid-rodriguez** [comment]
:+1: I'll remove the checkbox and use the participatory space scope as root for now.

**Comment by deivid-rodriguez** [comment]
Ok, so I'm having a look at the scoping and one question comes to my mind: What should happen if the participatory space scope is changed to a scope that's not an ancestor of the voting scope? Currently it renders the voting form infinitely invalid since the scope will never be valid and it can't be unset.

I can see two different approaches:

* Make sure that never happens. I think we would need to add hooks to the participatory space manifest in core for that...

* Don't make the validation at all. Make sure the root of the picker is the participatory space scope unless it is set to something else to improve user experience, but don't actually validate that the scope belongs to the participatory space scope when saving the form, only that it belongs to the organization scopes.

What do you think? I think we can go with the latter for now and think of adding the former at some point if we strongly feel it's necessary.

**Comment by leio10** [comment]
I think I fixed that problem un proposals and meetings forms. It just have to allow editing the voting scope and start with the root scope if the current os invalidez.

**Comment by deivid-rodriguez** [comment]
The same fix as the one you applied for meetings and proposals has been applied in #42 :smiley:. Closing this!
